/**
* SpringBoot
* SpringBoot Examples.
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package io.skambo.example.infrastructure.api.deleteuser.v1.dto

import io.skambo.example.infrastructure.api.common.dto.v1.Header

import com.squareup.moshi.Json
/**
 * 
 * @param header 
 */
data class DeleteUserResponse (
    @Json(name = "header")
    val header: io.skambo.example.infrastructure.api.common.dto.v1.Header
) {

}

