# Use root/example as user/password credentials
version: '3.1'

services:
  app:
    build:
      context: .
    command: ./start.sh
    volumes:
      - $HOME/.aws:/root/.aws
    ports:
      - 8080:8080
    depends_on:
      - db
    links:
      - db
    env_file:
      - compose.env


  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: 'sandra'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3308:3306'
    expose:
      # Opens port 3308 on the container
      - '3308'
      # Where our data will be persisted
    volumes:
      - sandra:/.db/mysql/data
# Names our volume
volumes:
  sandra:
