swagger: "2.0"
definitions:
  Header:
    type: object
    properties:
      messageId:
        type: string
      timestamp:
        type: string
        format: date-time
      responseStatus:
        $ref: "#/definitions/Status"
      groupId:
        type: string
      referenceId:
        type: string
      batch:
        $ref: "#/definitions/Batch"
    required:
      - messageId
      - timestamp

  Status:
    type: object
    properties:
      status:
        type: string
      errorCode:
        type: string
      errorMessage:
        type: string
    required:
      - status

  Batch:
    type: object
    properties:
      batchId:
        type: string
      messageSequenceNumber:
        type: integer
        format: int32
      totalMessages:
        type: integer
        format: int32
    required:
      - batchId
      - messageSequenceNumber
      - totalMessages

parameters:
  messageId:
    name: messageId
    in: header
    description: Message Id of the message, should be a GUID that matches the same field in the header.
    required: true
    type: string
  groupId:
    name: groupId
    in: header
    description: Id used to group related messages, should be a GUID that matches the same field in the header.
    required: false
    type: string
  timestamp:
    name: timestamp
    in: header
    description: Time message was sent
    required: false
    type: string
    format: date-time
  correlationId:
    name: correlationId
    in: header
    description: Id used to match request and response messages.
    required: false
    type: string
  returnAddress:
    name: returnAddress
    in: header
    description: Delivery address for the response message.
    required: false
    type: string
  priority:
    name: priority
    in: header
    description: Priority of the message.
    required: false
    type: string
