swagger: "2.0"
definitions:
  UserDTO:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      dateOfBirth:
        type: string
        format: date-time
      city:
        type: string
      email:
        type: string
      phoneNumber:
        type: string

