swagger: "2.0"
info:
  title: SpringBoot
  version: 1.0.0
  description: SpringBoot Examples.
host: 127.0.0.1:8080
externalDocs:
  description: GitHub README
  url: "https://github.com/skambo/kotlin"
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /api/v1/greeting:
    get:
      summary: Greeting API
      description: Greeting API
      parameters:
        - $ref: "common/common-1.yaml#/parameters/messageId" 
        - $ref: "common/common-1.yaml#/parameters/timestamp" 
        - $ref: "common/common-1.yaml#/parameters/groupId"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GreetingResponse"
        "400":
          description: Request Rejected
          schema:
            $ref: "#/definitions/GreetingResponse"
        "401":
          description: Request Unauthorized
          schema:
            $ref: "#/definitions/GreetingResponse"
        "500":
          description: Greeting Failed
          schema:
            $ref: "#/definitions/GreetingResponse"

securityDefinitions:
  ApiKeyAuth:
    type: apiKey
    in: header
    name: Authorization

definitions:
  GreetingResponse:
    type: object
    properties:
      header:
        $ref: "common/common-1.yaml#/definitions/Header"
      id:
        type: integer
        format: int64
      content:
        type: string