/**
* SpringBoot
* SpringBoot Examples.
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package io.skambo.example.infrastructure.api.greeting.v1.dto

import com.squareup.moshi.Json
/**
 * 
 * @param header 
 * @param id 
 * @param content 
 */
data class GreetingResponse (
    @Json(name = "header")
    val header: io.skambo.example.infrastructure.api.common.dto.v1.Header? = null,
    @Json(name = "id")
    val id: kotlin.Long? = null,
    @Json(name = "content")
    val content: kotlin.String? = null
) {

}

