name: PR pipeline

on: [push]

jobs:
  checkstyle:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run checkstyle main
        run: ./gradlew checkstyleMain
      - name: Run checkstyle test
        run: ./gradlew checkstyleTest

  unitTests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run unit tests
        run: ./gradlew unitTest

  integrationTests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run integration tests
        run: ./gradlew integrationTest
