/**
* 
* 
*
* 
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package io.skambo.example.infrastructure.api.common.dto.v1

import io.skambo.example.infrastructure.api.common.dto.v1.Batch
import io.skambo.example.infrastructure.api.common.dto.v1.Status

import com.squareup.moshi.Json
/**
 * 
 * @param messageId 
 * @param timestamp 
 * @param responseStatus 
 * @param groupId 
 * @param referenceId 
 * @param batch 
 */
data class Header (
    @Json(name = "messageId")
    val messageId: kotlin.String,
    @Json(name = "timestamp")
    val timestamp: java.time.OffsetDateTime,
    @Json(name = "responseStatus")
    val responseStatus: Status? = null,
    @Json(name = "groupId")
    val groupId: kotlin.String? = null,
    @Json(name = "referenceId")
    val referenceId: kotlin.String? = null,
    @Json(name = "batch")
    val batch: Batch? = null
) {

}

