/**
* 
* 
*
* 
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package io.skambo.example.infrastructure.api.common.dto.v1


import com.squareup.moshi.Json
/**
 * 
 * @param id 
 * @param name 
 * @param dateOfBirth 
 * @param city 
 * @param email 
 * @param phoneNumber 
 */
data class UserDTO (
    @Json(name = "id")
    val id: kotlin.Long? = null,
    @Json(name = "name")
    val name: kotlin.String? = null,
    @Json(name = "dateOfBirth")
    val dateOfBirth: java.time.OffsetDateTime? = null,
    @Json(name = "city")
    val city: kotlin.String? = null,
    @Json(name = "email")
    val email: kotlin.String? = null,
    @Json(name = "phoneNumber")
    val phoneNumber: kotlin.String? = null
) {

}

